name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: set up JDK 18
      uses: actions/setup-java@v4
      with:
        java-version: '18'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Clean Bulid
      run: ./gradlew clean
      
    - name: Run lint
      run: ./gradlew lintDebug -Dlint.baselines.continue=true --continue
    - name: Upload lint report # 빌드 리포트를 저장하는 위치를 지정 GitHub Actions의 artifacts에 저장
      uses: actions/upload-artifact@v3
      with:
        name: lint-report
        path: app/build/reports/lint-results-debug.html
    - name: Download a Build Artifact # 빌드 리포트 다운로드
      uses: actions/download-artifact@v4.1.8
      
    - name: Build with Gradle
      run: ./gradlew build --stacktrace --continue
      # run: ./gradlew build
      
    - name: hello world
      run: echo "Hello World!!"
